name: Build SigWatch

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'
      - 'Screenshot/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'
      - 'Screenshot/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Qt (MinGW)
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        modules: 'qtmultimedia qtcharts'
        tools-only: false

    - name: Add MinGW to PATH
      run: |
        echo "C:\Qt\Tools\mingw1120_64\bin" >> $env:GITHUB_PATH

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"

    - name: Build
      run: |
        cmake --build build --config Release -j 4

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SigWatch-Windows-Package
        path: build/Release/SigWatch.exe
